### PR TITLE
Pull Request for Issue #272 (Executable FatJar)

### PR DESCRIPTION
**Pull request by nickman**
Modifications to create an executable standalone FatJar.
Depends on Issue #271.
Fully documented on group:  https://groups.google.com/forum/?fromgroups#!topic/opentsdb/jx0JIPadDXk

### CODE REVIEW

**Comment by manolama** [comment]
Woops, I think this one blew out because I waited too long. Would you be able to submit the FatJar again?

**Comment by nickman** [comment]
Will do.

**Comment by longtimeago** [comment]
@nickman seems like this very nice intention is abandoned?
That's sad :(

**Comment by johann8384** [comment]
I am improving the build system and simplifying it. This will happen for
2.3.something.
On Aug 27, 2016 1:20 AM, "Paul Polishchuk" <notifications@github.com> wrote:

@nickman <https://github.com/nickman> seems like this very nice intention
is abandoned?
That's sad :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenTSDB/opentsdb/pull/282#issuecomment-242899402>, or mute
the thread

**Comment by longtimeago** [comment]
@johann8384 thank you! it's nice to hear that :)

**Pull request closed without merging**
