### PR TITLE
Support for downsample fill policies

### PR DESCRIPTION
**Pull request by sumannewton**

### CODE REVIEW

**Comment by sumannewton** [comment]
Review & merge if no issues observed.

**Comment by sumannewton** [comment]
@manolama Review & merge.

**Comment by sumannewton** [comment]
@tsuna @manolama

**Comment by IDerr** [comment]
I think they are not available for the moment, perhaps some holidays, not useful to ping them everyday :)

**Comment by sumannewton** [comment]
@johann8384  There are no docs for this tool. Documentation is within the python script itself which explain the significance of each and every option param in command. Let me know if anything else is needed.

**Comment by sumannewton** [comment]
@manolama @tsuna Any update?

**Comment by johann8384** [comment]
@sumannewton Can you rebase this against `next` rather than `master`? I can merge it to `next`.

**Comment by johann8384** [comment]
Docs for this tool:

http://opentsdb.net/docs/build/html/user_guide/utilities/nagios.html

https://github.com/OpenTSDB/opentsdb.net/blob/gh-pages/docs/source/user_guide/utilities/nagios.rst

**Comment by johann8384** [comment]
Actually, this can merge to `master`, since it isn't in the code, shouldn't be an issue when we go next->master for the release.

**Pull request merged**
