### PR TITLE
Update javassist-3.18.1-GA.jar.md5

### PR DESCRIPTION
**Pull request by goll**
Updated md5sum from http://central.maven.org/maven2/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar.md5 since the build was failing with:
```
error: invalid checksum for third_party/javassist/javassist-3.18.1-GA.jar
error: expected: 5bb83868c87334320562af7eded65cc2
error:    found: a170b370a10d2f36e5adceb057f82067
Makefile:2160: recipe for target 'third_party/javassist/javassist-3.18.1-GA.jar' failed
make[1]: Leaving directory '/opt/opentsdb/opentsdb-2.3.0/build'
make[1]: *** [third_party/javassist/javassist-3.18.1-GA.jar] Error 1
Makefile:1370: recipe for target 'all' failed
make: *** [all] Error 2
```

Both build.sh and build-bigtable.sh from the v2.3.0 tag fail with the same error^.

### CODE REVIEW

**Comment by trixpan** [comment]
@goll I face this issue as well https://github.com/OpenTSDB/opentsdb/issues/928

However, have we validated the new hash is safe? I noticed it has been around for a while

VirusTotal metadata
First submission 2013-12-22 10:49:35 UTC ( 3 years, 1 month ago )
Last submission 2017-01-31 04:54:58 UTC ( 5 hours, 55 minutes ago )
File names	javassist-3.18.1-GA.jar

but I wonder how come the old MD5 suddenly isn't valid anymore, specially when it has also be seen in the past?

 VirusTotal metadata
First submission 2013-12-16 13:17:02 UTC ( 3 years, 1 month ago )
Last submission 2017-01-18 04:45:48 UTC ( 1 week, 6 days ago )

**Comment by ftorto** [comment]
Just for information, 

I googled old md5, I found : http://grepcode.com/snapshot/repo1.maven.org/maven2/org.javassist/javassist/3.18.1-GA
but if I follow links, I have new hash in .md5 file and also after recomputing it

but I also found:
http://grepcode.com/snapshot/repository.jboss.org/nexus/content/repositories/releases/org.javassist/javassist/3.18.1-GA
with new md5

**Comment by paulsr87** [comment]
Anyone going to open the PR soon?
Thanks.

**Comment by trixpan** [comment]
Got a reply from Redhats security team and so far they believe the mismatch is caused by deferring timestamps and point to the fact the MD5 of the JAR available included in the following [compressed file](https://github.com/jboss-javassist/javassist/archive/rel_3_18_1_ga.zip) is also different:

**Comment by manolama** [comment]
Hmm, since this could still affect folks using different mirrors it may be better to just bump the version to the latest stable version 3.21.0-GA. @goll would you mind re-issuing with that change then I can merge it into maint, master and next?

**Comment by goll** [comment]
Sure @manolama. Working on the commit to bump javassist to 3.21.0-GA.

**Comment by manolama** [comment]
Thanks! Merged in b81ef90b6777295e780bbd38ca541f26e97b3648.

**Pull request closed without merging**
