### PR TITLE
Filter out duplicate queries

### PR DESCRIPTION
**Pull request by hzy001**
Signed-off-by: Hao Ziyu haoziyu@qiyi.com

### CODE REVIEW

**Comment by johann8384** [comment]
Before your code changes can be included, please file the [Contribution License Agreement](https://docs.google.com/spreadsheet/embeddedform?formkey=dFNiOFROLXJBbFBmMkQtb1hNMWhUUnc6MQ).

**Comment by hzy001** [comment]
Done

**Comment by manolama** [comment]
Any chance of getting a couple of UTs to verify the dupes are removed? Looks good and we can add it to 2.3.1.

**Comment by hzy001** [comment]
I will provide some UTs later

**Comment by manolama** [comment]
Merged in 99cfc5090100b5df303b264cf375477ebcc906ed. Thanks!

**Pull request closed without merging**
