### PR TITLE
Update scripts + config in build-aux/deb

### PR DESCRIPTION
**Pull request by jf**

### CODE REVIEW

**Comment by IDerr** [comment]
Hi,

as said in https://github.com/OpenTSDB/opentsdb/pull/1073, we should keep java7 for 2.4

**Comment by jf** [comment]
I certain didn't know that. Thanks, @IDerr !

**Comment by IDerr** [comment]
I'll close my PR, you have done more commits than me :P

**Comment by jf** [comment]
apologies, @IDerr , I certainly didnt know that you had done a similar PR for the init script already! Thank you for being so gracious.

**Comment by IDerr** [comment]
No need to apologies, you have done a better job than mine :D

**Comment by johann8384** [comment]
@jf can we get this rebased to the `next` branch?

**Comment by jf** [comment]
@johann8384 do you mean make another PR for `next`?

**Comment by johann8384** [comment]
Nope, I just merged it to master and will cherry pick to next.

On Nov 28, 2017 6:55 PM, "jf" <notifications@github.com> wrote:

@johann8384 <https://github.com/johann8384> do you mean make another PR for
next?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenTSDB/opentsdb/pull/1103#issuecomment-347715989>,
or mute
the thread

**Pull request merged**
