### PR TITLE
Support Ganglia v30x and v31x protocols.

### PR DESCRIPTION
**Pull request by jesse5e**
- Opens an UDP port (8649) to receive Ganglia v30x and v31x protocol messages.
- Decodes Ganglia messages using gmetric4j and xdr.
- Inserts just numeric metrics to OpenTSDB.
- Added ganglia version, hostname, ip address, and optionally cluster name to
  the metric as tags.
- Ignored units.
- Ignored string metrics.
- Collected Ganglia RPC statistics.
- Ganglia support is disabled by default.

### CODE REVIEW

**Comment by manolama** [comment]
Looks good but could you create a full repo for it similar to the plugins I was poking around with please? Thanks!

**Comment by jesse5e** [comment]
Chris,

I'm guessing that you are suggesting Ganglia plugin source files have its
own new repository.

I'd like to use Maven to build a Ganglia plugin jar, but I cannot create
the dependency on OpenTSDB such as the following.

    <dependency>
      <groupId>net.opentsdb</groupId>
      <artifactId>opentsdb</artifactId>
      <version>2.1.0</version>
    </dependency>

It would be nice if you could upload OpenTSDB jars to either
mvnrepository.com or org.sonatype.oss.

**Comment by johann8384** [comment]
@jesse5e did you happen to create a repository for this plugin? I can put it with mine if you want, and are comfortable with the GPLv3 license:  https://github.com/inst-tech/opentsdb-plugins

Also, the Maven dependency should work from here: https://mvnrepository.com/artifact/net.opentsdb/opentsdb/2.3.0

**Comment by johann8384** [comment]
It didn't look like there were any changes to merge in once this plugin has it's own stand-alone home.

**Pull request closed without merging**
