### PR TITLE
add first and last aggregator

### PR DESCRIPTION
**Pull request by andyflury**
It looks like first and last aggregators are currently missing. This is important when trying to aggregate financial tick data into high-low-open-close Bars. Would you be so kind as to verify these changes make sense? Thanks Andy Flury

### CODE REVIEW

**Comment by manolama** [comment]
Yeah, I think they make sense if you're using them on downsamplers. But it may be useful to throw an exception if someone tries to use them for group by aggregation as it doesn't work for grouping as we don't order the results in any particular fashion.
Also would you mind throwing in a couple of UTs please? Thanks!

**Comment by andyflury** [comment]
Hi Chris

 

Sure, I’ll be glad to add this but how do I know if the Aggregation method is getting called by grouping instead of down sampling?

 

Also, would you be so kind as to point me to some similar unit tests that I could reuse to add additional tests?

 

Regards

Andy

**Comment by manolama** [comment]
Thanks Andy! Check out https://github.com/OpenTSDB/opentsdb/blob/next/test/core/TestTsdbQueryDownsample.java for unit tests around downsampling, just plugin your first/last aggs.

For checking to see if the aggregator would be used for group bys, take a look at https://github.com/OpenTSDB/opentsdb/blob/next/src/core/TsdbQuery.java#L300 and the ``TsdbQuery.setTimeseries()`` methods.

**Comment by andyflury** [comment]
Thanks, I had a look at the links but I’m afraid I’ll have to leave that up to you guys. Aggregators.java was quite straight forward to modify but it looks like modifying the UnitTests and TsdbQuery would require a bit more knowledge of the internals of TSDB.

**Comment by manolama** [comment]
Added in 535b7e553812d1f2c13377d57e352e5c131a4097. Thanks!

**Pull request closed without merging**
