### PR TITLE
Extend an aggregator of SquareSum, which returns the square sum of th…

### PR DESCRIPTION
**Pull request by Eduardo95**
…e data point. This might be useful in some scientific calculations

### CODE REVIEW

**Comment by johann8384** [comment]
Can we get some tests for this and get it rebased against "next"?

**Comment by Eduardo95** [comment]
@johann8384 OK, I will write some unit tests, then maybe you can rebase it against branch "next".

**Comment by Eduardo95** [comment]
I notices that there are not many unit tests for aggregators like sum or avg. I wrote some tests for squareSum, covering few data inputs and random data inputs. Please check if this is suitable for a merge request. Thanks. @johann8384

**Comment by manolama** [comment]
Merged in 13128461d34833cfec04a68f664466d304ba3432

**Pull request closed without merging**
