### PR TITLE
V2.1.0 hbase counters

### PR DESCRIPTION
**Pull request by pinifaran**
1. added support for using hbase counters as the underlying implementation of opentsdb
2. added support for summing up detected duplicate counters (instead of discarding them)

### CODE REVIEW

**Comment by johann8384** [comment]
@pinifaran have you been using these changes at scale anywhere?

**Comment by pinifaran** [comment]
Yes. it already passed load tests at our lab and we're about to use it in production.

**Comment by johann8384** [comment]
@pinifaran Can you rebase this off of the NEXT branch instead of MASTER?

**Comment by johann8384** [comment]
I'm closing, because this, but I'll be looking out for a new PR based off opentsdb:next instead.

**Comment by pinifaran** [comment]
Hi, i create a new Pull Request to opentsdb:next branch:  
HBase counters #758 

Thanks.

**Pull request closed without merging**
